name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-lowest-version:
    name: Build lowest version
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          coverage: 'none'
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --prefer-stable --prefer-lowest --no-progress

      - name: Run tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: 'none'
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Mimic PHP 8.0
        run: composer config platform.php 8.0.999
        if: matrix.php > 8

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run tests
        run: make test
